stages:
  - build
  - deploy

variables:
  IMAGE_NAME: $DOCKER_USERNAME/devops-pipeline-aws

# STAGE 1 — BUILD & PUSH DOCKER IMAGE

build:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  script:
    - docker build -f docker/Dockerfile -t $IMAGE_NAME:latest ./app
    - docker push $IMAGE_NAME:latest

# STAGE 2 — DEPLOY VIA ANSIBLE

deploy:
  stage: deploy
  image: python:3.11
  before_script:
    - pip install ansible -q
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/testkey
    - chmod 600 ~/.ssh/testkey
    - echo "[ec2]" > ansible/inventory.ini
    - echo "$EC2_IP ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/testkey" >> ansible/inventory.ini
  script:
    - cd ansible && ansible-playbook playbook.yml